"""fias

Revision ID: d88986372092
Revises: a57262046435
Create Date: 2024-07-20 14:51:52.306666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88986372092'
down_revision: Union[str, None] = 'a57262046435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('fias_id', sa.String(length=300), nullable=True))
    op.drop_index('ix_cities_lat', table_name='cities')
    op.drop_index('ix_cities_lon', table_name='cities')
    op.create_index(op.f('ix_cities_fias_id'), 'cities', ['fias_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_fias_id'), table_name='cities')
    op.create_index('ix_cities_lon', 'cities', ['lon'], unique=False)
    op.create_index('ix_cities_lat', 'cities', ['lat'], unique=False)
    op.drop_column('cities', 'fias_id')
    # ### end Alembic commands ###
